apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  # labels of deployment resource
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: khalidaws2024/app2:1.0.0.0
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app2
spec:
  selector: # labels are used as selectors
    app: app2
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:891377396025:certificate/95a8c826-45ec-4c96-aeaf-37e890f3658c
    alb.ingress.kubernetes.io/group.name: joindevops
    

spec:
  ingressClassName: alb
  rules:
  - host: "app2.khalidaws82.tech"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80